### ISSUE TITLE
Can't load methods/properties by importing from specific section

### ISSUE THREAD

**Issue by movingobjects** [movingobjects/varyd-utils#2]
I want to allow access to specific pieces of a section in the following way:

```js
import { lerp } from 'varyd-utils/math';
```

But, I'm not able to access `math` in this way how things are set up.

**Comment by alexburner** [comment]
If you did top-level source files (I also mention [here](https://github.com/sccottt/varyd-utils/issues/1#issuecomment-323497750)) users could do stuff like:

All files in a namespace:
```js
import * as vutil from 'varyd-util'; // imports node_modules/varyd/index.js
vutil.math.lerp();
```

Single file in a namespace:
```js
import * as math from 'varyd-util/math'; // imports node_modules/varyd/math.js
math.lerp();
```

Single export from one file:
```js
import { lerp } from 'varyd-util/math'; // imports node_modules/varyd/math.js
lerp();
```

**Comment by alexburner** [comment]
But I'm not sure how this plays with building files / compatibility issues

I wanna hope any end user would be capable of building with whatever webpack/babel/etc?

**Comment by movingobjects** [comment]
Yay, this works moving everything top-level.

**Comment by alexburner** [comment]
woohoo!
